import './style.css';
import {Story} from 'inkjs';
import {movements,characters,references,lineage} from './data.js';
const app=document.querySelector('#app');
app.innerHTML=`
<header class="nav"><a class="mark" href="#top"><span>BTB</span> Battle the Beast</a><nav><a href="#atlas">Story atlas</a><a href="#play">Enter story</a><a href="#lineage">Design lineage</a><a href="#overlap">Syfy overlap</a></nav></header>
<main id="top">
<section class="hero"><div class="hero-copy"><p class="eyebrow">A nonlinear story archive by IBLoud</p><h1>The cycle can’t be broken.<br><em>It must be mended.</em></h1><p class="lede">An interactive atlas of fractured timelines, persistent memory, distributed power, and the people who learn that survival is a cooperative spell.</p><div class="actions"><a class="primary" href="#play">Enter the story</a><a class="secondary" href="#atlas">Trace the timeline</a></div></div><div class="orbit" aria-label="A fractured circular timeline"><div class="ring r1"></div><div class="ring r2"></div><div class="core">∞</div><span class="node n1">Luna</span><span class="node n2">Penny</span><span class="node n3">Julia</span><span class="node n4">Aster</span><span class="node n5">Q</span></div></section>
<section class="thesis"><p>Not a conventional chronology</p><blockquote>Every story is a shard. Together, they form the hidden architecture of a narrative game.</blockquote><div class="legend"><span><i class="gold"></i>Original story</span><span><i class="blue"></i>Syfy intersection</span><span><i class="rose"></i>Recursive event</span></div></section>
<section id="atlas" class="section"><div class="section-head"><p class="eyebrow">The causal spine</p><h2>Seven movements through a broken world</h2><p>Read in the order the structure reveals itself—not necessarily the order events occurred.</p></div><div class="timeline">${movements.map(m=>`<article class="movement"><div class="count">${m.n}</div><div><p class="work">${m.work}</p><h3>${m.title}</h3><p>${m.summary}</p><div class="tags">${m.characters.map(c=>`<span>${c}</span>`).join('')}</div></div><button aria-label="Show series overlap for ${m.title}">View overlap <b>＋</b></button><div class="overlap-panel"><p class="label">Syfy reference points</p>${m.overlaps.map(o=>`<p>${o}</p>`).join('')}</div></article>`).join('')}</div></section>
<section id="play" class="play-section"><div class="section-head"><p class="eyebrow">Playable prototype · powered by ink</p><h2>Enter through the fountain</h2><p>Your choices change what you carry into the convergence.</p></div><div class="reader"><div class="reader-bar"><span>THE NEITHERLANDS</span><button id="restart">Restart ↻</button></div><div id="story" aria-live="polite"></div><div id="choices"></div></div></section>
<section class="section"><div class="section-head"><p class="eyebrow">The ensemble</p><h2>No singular chosen one</h2><p>Each character holds one necessary power. Isolation turns the gift destructive.</p></div><div class="character-grid">${characters.map(([n,r,d])=>`<article><span>${r}</span><h3>${n}</h3><p>${d}</p></article>`).join('')}</div></section>
<section id="lineage" class="section lineage"><div class="section-head"><p class="eyebrow">From story system to strategy system</p><h2>The prototype for Veiled Dominion</h2><p>Battle the Beast was a narrative laboratory. Veiled Dominion translates its original design questions into franchise-neutral, testable mechanics.</p></div><div class="lineage-rule"><strong>Transfer the principle—not the IP.</strong><span>This archive is historical design provenance. It does not set current Veiled Dominion rules.</span></div><div class="lineage-grid">${lineage.map(([source,principle,mechanic])=>`<article><p class="source">${source}</p><div class="arrow">→</div><p>${principle}</p><h3>${mechanic}</h3></article>`).join('')}</div><div class="invariant"><span>Veiled Dominion project invariant</span><blockquote>Power becomes mastery through restraint.</blockquote><a href="https://github.com/Loptr-Lab/veiled-dominion-engine/blob/main/docs/design/GDD.md">Read the canonical game design document ↗</a></div></section>
<section id="overlap" class="section overlap"><div class="section-head"><p class="eyebrow">Canon compass</p><h2>Where the stories touch the Syfy series</h2><p>These are interpretive correspondences, not claims that original additions are series canon.</p></div><div class="reference-table">${references.map(([s,c,n])=>`<div class="ref"><h3>${s}</h3><span>${c}</span><p>${n}</p></div>`).join('')}</div><aside><strong>Transformative-work note</strong><p>Battle the Beast is an unofficial transformative fan project inspired by Lev Grossman’s novels and Syfy’s television adaptation of <i>The Magicians</i>. Original characters, alternate origins, and the connective narrative architecture are identified separately.</p></aside></section>
</main><footer><span>Battle the Beast · IBLoud</span><span>Written in ink · Built as an archive of becoming</span></footer>`;
document.querySelectorAll('.movement button').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('.movement');const open=card.classList.toggle('open');button.querySelector('b').textContent=open?'−':'＋'}));
let story;const storyEl=document.querySelector('#story');const choicesEl=document.querySelector('#choices');
async function start(){const json=await fetch(`${import.meta.env.BASE_URL}story/battle-the-beast.json`).then(r=>r.json());story=new Story(json);storyEl.innerHTML='';render()}
function render(){while(story.canContinue){const text=story.Continue().trim();const tags=story.currentTags;if(text){const speaker=tags.find(t=>t.startsWith('speaker:'))?.split(':')[1];const chapter=tags.find(t=>t.startsWith('chapter:'))?.slice(8);if(chapter)storyEl.insertAdjacentHTML('beforeend',`<p class="chapter">${chapter}</p>`);storyEl.insertAdjacentHTML('beforeend',`<p class="line">${speaker?`<b>${speaker}</b>`:''}${text}</p>`)}}choicesEl.innerHTML='';story.currentChoices.forEach((choice,i)=>{const button=document.createElement('button');button.textContent=choice.text;button.addEventListener('click',()=>{story.ChooseChoiceIndex(i);render()});choicesEl.append(button)});if(!story.currentChoices.length)choicesEl.innerHTML='<button id="again">Return to the fountain</button>';document.querySelector('#again')?.addEventListener('click',start);storyEl.lastElementChild?.scrollIntoView({behavior:'smooth',block:'nearest'})}
document.querySelector('#restart').addEventListener('click',start);start();
